import { Schema } from "../types";
import { GITHUB_URL } from "../config/constants";

export const APPLICATION_SCHEMA: Schema = {
  $id: `${GITHUB_URL}/schemas/application/1.0.0`,
  source: GITHUB_URL,
  name: 'Application',
  title: 'Application',
  version: '1.0.0',
  description: 'An application, service, or dApp within the organization.',
  attributes: [
    {
      name: 'name',
      type: 'string',
      key: 'name',
      description: 'The name of the application',
      isRequired: false,
    },
    {
      name: 'description',
      type: 'string',
      key: 'description',
      description: 'Description of the application\'s purpose and functionality',
      isRequired: false,
    },
    {
      name: 'url',
      type: 'string',
      key: 'url',
      description: 'URL where the application is hosted or accessed',
      format: 'uri',
      isRequired: false,
    },
    {
      name: 'repository',
      type: 'string',
      key: 'repository',
      description: 'Source code repository URL',
      isRequired: false,
    },
    {
      name: 'version',
      type: 'string',
      key: 'version',
      description: 'Current version of the application',
      isRequired: false,
    },
    {
      name: 'status',
      type: 'string',
      key: 'status',
      description: 'Application status (e.g., Active, Development, Deprecated)',
      isRequired: false,
    },
  ],
  type: 'object' as const,
  properties: {
    class: {
      name: 'class',
      type: 'string',
      key: 'class',
      description: 'The class of the application',
      isRequired: false,
    },
    name: {
      name: 'name',
      type: 'string',
      key: 'name',
      description: 'The name of the application',
      isRequired: false,
    },
    description: {
      name: 'description',
      type: 'string',
      key: 'description',
      description: 'Description of the application\'s purpose and functionality',
      isRequired: false,
    },
    url: {
      name: 'url',
      type: 'string',
      key: 'url',
      description: 'URL where the application is hosted or accessed',
      format: 'uri',
      isRequired: false,
    },
    repository: {
      name: 'repository',
      type: 'string',
      key: 'repository',
      description: 'Source code repository URL',
      isRequired: false,
    },
    version: {
      name: 'version',
      type: 'string',
      key: 'version',
      description: 'Current version of the application',
      isRequired: false,
    },
    status: {
      name: 'status',
      type: 'string',
      key: 'status',
      description: 'Application status (e.g., Active, Development, Deprecated)',
      isRequired: false,
    },
  },
}
