import { GITHUB_URL } from "../config/constants";
import { Schema } from "../types";

export const CONTRACT_SCHEMA: Schema = {
  $id: `${GITHUB_URL}/schemas/contract/1.1.1`,
  source: GITHUB_URL,
  title: 'Contract',
  version: '1.1.1',
  description:
    'Smart contract metadata profile following Enscribe smart contract metadata format.',
  type: 'object' as const,
  properties: {
    alias: {
      type: 'string',
      description: 'Human-readable contract alias (ENSIP-18 alias)',
      isRequired: false,
    },
    description: {
      type: 'string',
      description: 'Short description of the contract purpose (ENSIP-18 description)',
      isRequired: false,
    },
    avatar: {
      type: 'string',
      description: 'Avatar URI for the contract profile (ENSIP-12 avatar)',
      isRequired: false,
    },
    category: {
      type: 'string',
      description: 'Contract category (e.g., defi, gaming, dao, utility, proxy, factory)',
      isRequired: false,
    },
    license: {
      type: 'string',
      description: 'Official software license identifier for the source code',
      isRequired: false,
    },
    docs: {
      type: 'string',
      description: 'Primary documentation URL for developers and users',
      format: 'uri',
      isRequired: false,
    },
    'compiled-metadata': {
      type: 'string',
      description:
        'A URI to a contract metadata file as generated by a Solidity or Vyper compiler',
      isRequired: false,
    },
    audits: {
      type: 'json',
      description: 'JSON array of third-party audit reports',
      isRequired: false,
    },
  },
};
