import { GITHUB_URL } from "../config/constants";
import { Schema } from "../types";

export const CONTRACT_SCHEMA: Schema = {
  $id: 'https://github.com/0xLighthouse/ens-node-metadata/schemas/contract/1.1.1',
  source: GITHUB_URL,
  name: 'Contract',
  title: 'Contract',
  version: '1.1.1',
  description:
    'Smart contract metadata profile following Enscribe smart contract metadata format.',
  attributes: [
    {
      name: 'alias',
      type: 'string',
      key: 'alias',
      description: 'Human-readable contract alias (ENSIP-18 alias)',
      isRequired: false,
      notes: 'Lower-friction display name for wallets, explorers, and apps.',
    },
    {
      name: 'description',
      type: 'string',
      key: 'description',
      description: 'Short description of the contract purpose (ENSIP-18 description)',
      isRequired: false,
    },
    {
      name: 'avatar',
      type: 'string',
      key: 'avatar',
      description: 'Avatar URI for the contract profile (ENSIP-12 avatar)',
      isRequired: false,
    },
    {
      name: 'category',
      type: 'string',
      key: 'category',
      description: 'Contract category (e.g., defi, gaming, dao, utility, proxy, factory)',
      isRequired: false,
    },
    {
      name: 'license',
      type: 'string',
      key: 'license',
      description: 'Official software license identifier for the source code',
      isRequired: false,
    },
    {
      name: 'docs',
      type: 'string',
      key: 'docs',
      description: 'Primary documentation URL for developers and users',
      format: 'uri',
      isRequired: false,
    },
    {
      name: 'compiledMetadata',
      type: 'string',
      key: 'compiled-metadata',
      description:
        'A URI to a contract metadata file as generated by a Solidity or Vyper compiler',
      isRequired: false,
      notes:
        'Text record form uses URI. Resolver profile supports multichain lookup by coinType and contentType.',
    },
    {
      name: 'audits',
      type: 'json',
      key: 'audits',
      description: 'JSON array of third-party audit reports',
      isRequired: false,
    }
  ],
  type: 'object' as const,
  properties: {
    alias: {
      name: 'alias',
      type: 'string',
      key: 'alias',
      description: 'Human-readable contract alias (ENSIP-18 alias)',
      isRequired: false,
      notes: 'Lower-friction display name for wallets, explorers, and apps.',
    },
    description: {
      name: 'description',
      type: 'string',
      key: 'description',
      description: 'Short description of the contract purpose (ENSIP-18 description)',
      isRequired: false,
    },
    avatar: {
      name: 'avatar',
      type: 'string',
      key: 'avatar',
      description: 'Avatar URI for the contract profile (ENSIP-12 avatar)',
      isRequired: false,
    },
    category: {
      name: 'category',
      type: 'string',
      key: 'category',
      description: 'Contract category (e.g., defi, gaming, dao, utility, proxy, factory)',
      isRequired: false,
    },
    license: {
      name: 'license',
      type: 'string',
      key: 'license',
      description: 'Official software license identifier for the source code',
      isRequired: false,
    },
    docs: {
      name: 'docs',
      type: 'string',
      key: 'docs',
      description: 'Primary documentation URL for developers and users',
      format: 'uri',
      isRequired: false,
    },
    'compiled-metadata': {
      name: 'compiledMetadata',
      type: 'string',
      key: 'compiled-metadata',
      description:
        'A URI to a contract metadata file as generated by a Solidity or Vyper compiler',
      isRequired: false,
      notes:
        'Text record form uses URI. Resolver profile supports multichain lookup by coinType and contentType.',
    },
    audits: {
      name: 'audits',
      type: 'json',
      key: 'audits',
      description: 'JSON array of third-party audit reports',
      isRequired: false,
    },
  },
};
